<?php
$productList = $this->getList();
$data = $productList->getData();
$helper = $this->helper('Cybage\Quotation\Helper\Data');
?>


<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <th class="col-product"><span>Product</span></th>
                <th class="col-product"><span>Quantity</span></th>
                <th class="col-price-original"><span>Product Price</span></th>
                <th class="col-price"><span>Proposed Price</span></th>
            </tr>
        </thead>
        <tbody class="even">
            <?php
            foreach ($data as $list):
                $actualPrice = $list['total_product_price'];
                $proposedPrice = $list['total_proposed_price'];
                $imgAtt = [];
                if ($list['type_id'] == 'configurable') {
                    $imgAtt = $helper->getConfigurableProductImaege($list['product_id'], unserialize($list['options']));
                }
                ?>
                <tr>
                    <td class="col-product"><div id="order_item_2">
                            <div id="order_item_2_title" class="product-title">
                                <?php echo $list['name']; ?>
                                <?php
                                /*$options = @ $imgAtt['att'];*/

                                if (!empty($imgAtt) && $list['type_id'] == 'configurable') {
                                    echo '<br/>';
                                    foreach ($imgAtt['att'] as $okey => $ovalue) {
                                        echo $okey . ' : ' . $ovalue . '<br/>';
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    </td>
                    <td><?php echo $list['qty']; ?></td>
                    <td class="col-status"><?php echo $this->priceFormat($list['product_price']); ?></td>
                    <td class="col-price-original"><span class="price"><?php echo $this->priceFormat($list['proposed_price']); ?></span></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="2" ></td>
                <td ><b><?php echo __('Actual Price:') ?></b></td>
                <td><?php echo $this->priceFormat($actualPrice); ?></td>
            </tr> 
            <tr>
                <td colspan="2" ></td>
                <td><b><?php echo __('Proposed Price:') ?></b></td>
                <td><?php echo $this->priceFormat($proposedPrice); ?></td>
            </tr> 
        </tbody>
    </table>
</div>